# Generated by Django 4.0.6 on 2022-08-08 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Articles',
        ),
    ]
