# Generated by Django 4.0.6 on 2022-08-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_rename_products_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
